# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lz/orwell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lz/orwell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/lz/cmake-3.14.5-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/lz/cmake-3.14.5-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lz/orwell/CMakeFiles /home/lz/orwell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lz/orwell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named orwell

# Build rule for target.
orwell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orwell
.PHONY : orwell

# fast build rule for target.
orwell/fast:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/build
.PHONY : orwell/fast

#=============================================================================
# Target rules for targets named orwell_autogen

# Build rule for target.
orwell_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orwell_autogen
.PHONY : orwell_autogen

# fast build rule for target.
orwell_autogen/fast:
	$(MAKE) -f CMakeFiles/orwell_autogen.dir/build.make CMakeFiles/orwell_autogen.dir/build
.PHONY : orwell_autogen/fast

#=============================================================================
# Target rules for targets named myRtspClient

# Build rule for target.
myRtspClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myRtspClient
.PHONY : myRtspClient

# fast build rule for target.
myRtspClient/fast:
	$(MAKE) -f myRtspClient/CMakeFiles/myRtspClient.dir/build.make myRtspClient/CMakeFiles/myRtspClient.dir/build
.PHONY : myRtspClient/fast

#=============================================================================
# Target rules for targets named myRtspClient_autogen

# Build rule for target.
myRtspClient_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myRtspClient_autogen
.PHONY : myRtspClient_autogen

# fast build rule for target.
myRtspClient_autogen/fast:
	$(MAKE) -f myRtspClient/CMakeFiles/myRtspClient_autogen.dir/build.make myRtspClient/CMakeFiles/myRtspClient_autogen.dir/build
.PHONY : myRtspClient_autogen/fast

#=============================================================================
# Target rules for targets named jrtplib-shared

# Build rule for target.
jrtplib-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jrtplib-shared
.PHONY : jrtplib-shared

# fast build rule for target.
jrtplib-shared/fast:
	$(MAKE) -f myRtspClient/third_party/JRTPLIB/src/CMakeFiles/jrtplib-shared.dir/build.make myRtspClient/third_party/JRTPLIB/src/CMakeFiles/jrtplib-shared.dir/build
.PHONY : jrtplib-shared/fast

#=============================================================================
# Target rules for targets named jrtplib-static

# Build rule for target.
jrtplib-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jrtplib-static
.PHONY : jrtplib-static

# fast build rule for target.
jrtplib-static/fast:
	$(MAKE) -f myRtspClient/third_party/JRTPLIB/src/CMakeFiles/jrtplib-static.dir/build.make myRtspClient/third_party/JRTPLIB/src/CMakeFiles/jrtplib-static.dir/build
.PHONY : jrtplib-static/fast

#=============================================================================
# Target rules for targets named jrtplib-shared_autogen

# Build rule for target.
jrtplib-shared_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jrtplib-shared_autogen
.PHONY : jrtplib-shared_autogen

# fast build rule for target.
jrtplib-shared_autogen/fast:
	$(MAKE) -f myRtspClient/third_party/JRTPLIB/src/CMakeFiles/jrtplib-shared_autogen.dir/build.make myRtspClient/third_party/JRTPLIB/src/CMakeFiles/jrtplib-shared_autogen.dir/build
.PHONY : jrtplib-shared_autogen/fast

#=============================================================================
# Target rules for targets named jrtplib-static_autogen

# Build rule for target.
jrtplib-static_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jrtplib-static_autogen
.PHONY : jrtplib-static_autogen

# fast build rule for target.
jrtplib-static_autogen/fast:
	$(MAKE) -f myRtspClient/third_party/JRTPLIB/src/CMakeFiles/jrtplib-static_autogen.dir/build.make myRtspClient/third_party/JRTPLIB/src/CMakeFiles/jrtplib-static_autogen.dir/build
.PHONY : jrtplib-static_autogen/fast

FfmpegDecoder.o: FfmpegDecoder.cpp.o

.PHONY : FfmpegDecoder.o

# target to build an object file
FfmpegDecoder.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/FfmpegDecoder.cpp.o
.PHONY : FfmpegDecoder.cpp.o

FfmpegDecoder.i: FfmpegDecoder.cpp.i

.PHONY : FfmpegDecoder.i

# target to preprocess a source file
FfmpegDecoder.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/FfmpegDecoder.cpp.i
.PHONY : FfmpegDecoder.cpp.i

FfmpegDecoder.s: FfmpegDecoder.cpp.s

.PHONY : FfmpegDecoder.s

# target to generate assembly for a file
FfmpegDecoder.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/FfmpegDecoder.cpp.s
.PHONY : FfmpegDecoder.cpp.s

MediaStream.o: MediaStream.cpp.o

.PHONY : MediaStream.o

# target to build an object file
MediaStream.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/MediaStream.cpp.o
.PHONY : MediaStream.cpp.o

MediaStream.i: MediaStream.cpp.i

.PHONY : MediaStream.i

# target to preprocess a source file
MediaStream.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/MediaStream.cpp.i
.PHONY : MediaStream.cpp.i

MediaStream.s: MediaStream.cpp.s

.PHONY : MediaStream.s

# target to generate assembly for a file
MediaStream.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/MediaStream.cpp.s
.PHONY : MediaStream.cpp.s

OpenGlBufferQtQuick.o: OpenGlBufferQtQuick.cpp.o

.PHONY : OpenGlBufferQtQuick.o

# target to build an object file
OpenGlBufferQtQuick.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlBufferQtQuick.cpp.o
.PHONY : OpenGlBufferQtQuick.cpp.o

OpenGlBufferQtQuick.i: OpenGlBufferQtQuick.cpp.i

.PHONY : OpenGlBufferQtQuick.i

# target to preprocess a source file
OpenGlBufferQtQuick.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlBufferQtQuick.cpp.i
.PHONY : OpenGlBufferQtQuick.cpp.i

OpenGlBufferQtQuick.s: OpenGlBufferQtQuick.cpp.s

.PHONY : OpenGlBufferQtQuick.s

# target to generate assembly for a file
OpenGlBufferQtQuick.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlBufferQtQuick.cpp.s
.PHONY : OpenGlBufferQtQuick.cpp.s

OpenGlVideoQtQuick.o: OpenGlVideoQtQuick.cpp.o

.PHONY : OpenGlVideoQtQuick.o

# target to build an object file
OpenGlVideoQtQuick.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlVideoQtQuick.cpp.o
.PHONY : OpenGlVideoQtQuick.cpp.o

OpenGlVideoQtQuick.i: OpenGlVideoQtQuick.cpp.i

.PHONY : OpenGlVideoQtQuick.i

# target to preprocess a source file
OpenGlVideoQtQuick.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlVideoQtQuick.cpp.i
.PHONY : OpenGlVideoQtQuick.cpp.i

OpenGlVideoQtQuick.s: OpenGlVideoQtQuick.cpp.s

.PHONY : OpenGlVideoQtQuick.s

# target to generate assembly for a file
OpenGlVideoQtQuick.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlVideoQtQuick.cpp.s
.PHONY : OpenGlVideoQtQuick.cpp.s

OpenGlVideoQtQuick2.o: OpenGlVideoQtQuick2.cpp.o

.PHONY : OpenGlVideoQtQuick2.o

# target to build an object file
OpenGlVideoQtQuick2.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlVideoQtQuick2.cpp.o
.PHONY : OpenGlVideoQtQuick2.cpp.o

OpenGlVideoQtQuick2.i: OpenGlVideoQtQuick2.cpp.i

.PHONY : OpenGlVideoQtQuick2.i

# target to preprocess a source file
OpenGlVideoQtQuick2.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlVideoQtQuick2.cpp.i
.PHONY : OpenGlVideoQtQuick2.cpp.i

OpenGlVideoQtQuick2.s: OpenGlVideoQtQuick2.cpp.s

.PHONY : OpenGlVideoQtQuick2.s

# target to generate assembly for a file
OpenGlVideoQtQuick2.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/OpenGlVideoQtQuick2.cpp.s
.PHONY : OpenGlVideoQtQuick2.cpp.s

VideoConsumer.o: VideoConsumer.cpp.o

.PHONY : VideoConsumer.o

# target to build an object file
VideoConsumer.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoConsumer.cpp.o
.PHONY : VideoConsumer.cpp.o

VideoConsumer.i: VideoConsumer.cpp.i

.PHONY : VideoConsumer.i

# target to preprocess a source file
VideoConsumer.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoConsumer.cpp.i
.PHONY : VideoConsumer.cpp.i

VideoConsumer.s: VideoConsumer.cpp.s

.PHONY : VideoConsumer.s

# target to generate assembly for a file
VideoConsumer.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoConsumer.cpp.s
.PHONY : VideoConsumer.cpp.s

VideoProducer.o: VideoProducer.cpp.o

.PHONY : VideoProducer.o

# target to build an object file
VideoProducer.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoProducer.cpp.o
.PHONY : VideoProducer.cpp.o

VideoProducer.i: VideoProducer.cpp.i

.PHONY : VideoProducer.i

# target to preprocess a source file
VideoProducer.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoProducer.cpp.i
.PHONY : VideoProducer.cpp.i

VideoProducer.s: VideoProducer.cpp.s

.PHONY : VideoProducer.s

# target to generate assembly for a file
VideoProducer.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoProducer.cpp.s
.PHONY : VideoProducer.cpp.s

VideoSurface.o: VideoSurface.cpp.o

.PHONY : VideoSurface.o

# target to build an object file
VideoSurface.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoSurface.cpp.o
.PHONY : VideoSurface.cpp.o

VideoSurface.i: VideoSurface.cpp.i

.PHONY : VideoSurface.i

# target to preprocess a source file
VideoSurface.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoSurface.cpp.i
.PHONY : VideoSurface.cpp.i

VideoSurface.s: VideoSurface.cpp.s

.PHONY : VideoSurface.s

# target to generate assembly for a file
VideoSurface.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/VideoSurface.cpp.s
.PHONY : VideoSurface.cpp.s

common_example.o: common_example.cpp.o

.PHONY : common_example.o

# target to build an object file
common_example.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/common_example.cpp.o
.PHONY : common_example.cpp.o

common_example.i: common_example.cpp.i

.PHONY : common_example.i

# target to preprocess a source file
common_example.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/common_example.cpp.i
.PHONY : common_example.cpp.i

common_example.s: common_example.cpp.s

.PHONY : common_example.s

# target to generate assembly for a file
common_example.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/common_example.cpp.s
.PHONY : common_example.cpp.s

orwell_autogen/mocs_compilation.o: orwell_autogen/mocs_compilation.cpp.o

.PHONY : orwell_autogen/mocs_compilation.o

# target to build an object file
orwell_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/orwell_autogen/mocs_compilation.cpp.o
.PHONY : orwell_autogen/mocs_compilation.cpp.o

orwell_autogen/mocs_compilation.i: orwell_autogen/mocs_compilation.cpp.i

.PHONY : orwell_autogen/mocs_compilation.i

# target to preprocess a source file
orwell_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/orwell_autogen/mocs_compilation.cpp.i
.PHONY : orwell_autogen/mocs_compilation.cpp.i

orwell_autogen/mocs_compilation.s: orwell_autogen/mocs_compilation.cpp.s

.PHONY : orwell_autogen/mocs_compilation.s

# target to generate assembly for a file
orwell_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/orwell_autogen/mocs_compilation.cpp.s
.PHONY : orwell_autogen/mocs_compilation.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/orwell.dir/build.make CMakeFiles/orwell.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... orwell"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... orwell_autogen"
	@echo "... myRtspClient"
	@echo "... myRtspClient_autogen"
	@echo "... jrtplib-shared"
	@echo "... jrtplib-static"
	@echo "... jrtplib-shared_autogen"
	@echo "... jrtplib-static_autogen"
	@echo "... FfmpegDecoder.o"
	@echo "... FfmpegDecoder.i"
	@echo "... FfmpegDecoder.s"
	@echo "... MediaStream.o"
	@echo "... MediaStream.i"
	@echo "... MediaStream.s"
	@echo "... OpenGlBufferQtQuick.o"
	@echo "... OpenGlBufferQtQuick.i"
	@echo "... OpenGlBufferQtQuick.s"
	@echo "... OpenGlVideoQtQuick.o"
	@echo "... OpenGlVideoQtQuick.i"
	@echo "... OpenGlVideoQtQuick.s"
	@echo "... OpenGlVideoQtQuick2.o"
	@echo "... OpenGlVideoQtQuick2.i"
	@echo "... OpenGlVideoQtQuick2.s"
	@echo "... VideoConsumer.o"
	@echo "... VideoConsumer.i"
	@echo "... VideoConsumer.s"
	@echo "... VideoProducer.o"
	@echo "... VideoProducer.i"
	@echo "... VideoProducer.s"
	@echo "... VideoSurface.o"
	@echo "... VideoSurface.i"
	@echo "... VideoSurface.s"
	@echo "... common_example.o"
	@echo "... common_example.i"
	@echo "... common_example.s"
	@echo "... orwell_autogen/mocs_compilation.o"
	@echo "... orwell_autogen/mocs_compilation.i"
	@echo "... orwell_autogen/mocs_compilation.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

